server:
  port: 9101

spring:
  application:
    name: seedmall-auth
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${SEEDMALL_NACOS_ADDR:127.0.0.1:8848}
