server:
  port: 9106

spring:
  application:
    name: seedmall-order
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${SEEDMALL_NACOS_ADDR:127.0.0.1:8848}
  datasource:
    url: jdbc:mysql://${SEEDMALL_MYSQL_HOST:127.0.0.1}:${SEEDMALL_MYSQL_PORT:3306}/seedmall_order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${SEEDMALL_MYSQL_USERNAME:root}
    password: ${SEEDMALL_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${SEEDMALL_RABBITMQ_HOST:127.0.0.1}
    port: ${SEEDMALL_RABBITMQ_PORT:5672}
    username: ${SEEDMALL_RABBITMQ_USERNAME:guest}
    password: ${SEEDMALL_RABBITMQ_PASSWORD:guest}
