server:
  port: 9103

spring:
  application:
    name: seedmall-content
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${SEEDMALL_NACOS_ADDR:127.0.0.1:8848}
  datasource:
    url: jdbc:mysql://${SEEDMALL_MYSQL_HOST:127.0.0.1}:${SEEDMALL_MYSQL_PORT:3306}/seedmall_content?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${SEEDMALL_MYSQL_USERNAME:root}
    password: ${SEEDMALL_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SEEDMALL_REDIS_HOST:127.0.0.1}
      port: ${SEEDMALL_REDIS_PORT:6379}
rocketmq:
  name-server: ${SEEDMALL_ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: seedmall-content-producer
