server:
  port: 9105

spring:
  application:
    name: seedmall-seckill
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${SEEDMALL_NACOS_ADDR:127.0.0.1:8848}
  data:
    redis:
      host: ${SEEDMALL_REDIS_HOST:127.0.0.1}
      port: ${SEEDMALL_REDIS_PORT:6379}
  rabbitmq:
    host: ${SEEDMALL_RABBITMQ_HOST:127.0.0.1}
    port: ${SEEDMALL_RABBITMQ_PORT:5672}
    username: ${SEEDMALL_RABBITMQ_USERNAME:guest}
    password: ${SEEDMALL_RABBITMQ_PASSWORD:guest}
