server:
  port: 9000

spring:
  application:
    name: seedmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${SEEDMALL_NACOS_ADDR:127.0.0.1:8848}
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://seedmall-auth
          predicates:
            - Path=/auth/**
        - id: content
          uri: lb://seedmall-content
          predicates:
            - Path=/contents/**
        - id: product
          uri: lb://seedmall-product
          predicates:
            - Path=/products/**
        - id: seckill
          uri: lb://seedmall-seckill
          predicates:
            - Path=/seckill/**
        - id: order
          uri: lb://seedmall-order
          predicates:
            - Path=/orders/**
        - id: ai
          uri: lb://seedmall-ai
          predicates:
            - Path=/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
